server:
  port: 9091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_database
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:  # Ensure this key appears only once
      ddl-auto: update  # Options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Keep only one hibernate section
