server:
  port: 9091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_services
    username: javaguide
    password: javaguidepwd
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: host.docker.internal
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
